SWARM-Bot Firmware: swarm_bot_cpp/src/__dc_control__.c File Reference
__dc_control__.c File Reference
Header file for dc_control.c.
#include <__dc_control__.h>
Functions
int16_t _ref (uint8_t motor)
void _command (uint8_t motor, int16_t inputValue)
float _sens (uint8_t motor)
int _set_speed (uint8_t motor, int value)
void _break_motor (uint8_t motor)
void _init_dc_control (void)
int16_t _update_controller (uint8_t motor)
int16_t _dc_controller_loop (void)
Detailed Description
Header file for dc_control.c.
File: dc_control.h
Compiler: GCC-AVR
Supported devices: Tested on 328p
AppNote: ADC module driver
Author
Swarm robot graduation project workgroub
Mechatronics Program for the Distinguished
$Name$
Revision
1
$RCSfile$
Date
/19/2021 9:30:13 AM
Definition in file __dc_control__.c.
Function Documentation
_break_motor()
void _break_motor (uint8_t motor)
breaks the
Parameters
motor
Parameters
[in] motor motor MA or MB.
 {
     if (motor == MA)
     {
         _set_pwm_0A(0);
         _set_pwm_1A(0);
     }
     else if (motor == MB)
     {
         _set_pwm_0B(0);
         _set_pwm_1B(0);
     }
 }
Referenced by _set_speed().
_command()
void _command (uint8_t motor, int16_t inputValue)
Output command module for
Parameters
motor of value
inputValue
Parameters
[in] motor motor MA or MB.
[in] inputValue input value
 {
     _set_speed(motor,inputValue);
 }
References _set_speed().
_dc_controller_loop()
int16_t _dc_controller_loop (void)
PID DC controller loop
 {
     if(_controler_flag_A)
     {
          _update_controller(MA);
          _controler_flag_A = 0;
     }
     if(_controler_flag_B)
     {
         _update_controller(MB);
         _controler_flag_B = 0;
     }
     return 0;
 }
_init_dc_control()
void _init_dc_control (void)
Initialize the DC PID control module
 {
     pid_Init(K_P * SCALING_FACTOR, K_I * SCALING_FACTOR , K_D * SCALING_FACTOR , &pidData);
     sei();
 }
References pid_Init().
_ref()
int16_t _ref (uint8_t motor)
Reference for
Parameters
motor
Parameters
[in] motor motor MA or MB.
 {
     if(motor == MA)
     {
         return 20;
     }
     else if (motor == MB)
     {
         return 30;
     }
     return 0;
 }
Referenced by _update_controller().
_sens()
float _sens (uint8_t motor)
sensor module for
Parameters
motor
Parameters
[in] motor motor MA or MB.
 {
     if(motor == MA)
     {
         return (_omega_from_encA()*9.55);
     }
     else if (motor == MB)
     {
         return (_omega_from_encB()*9.55);
     }
     else
     {
         return -1;
     }
 }
Referenced by _update_controller().
_set_speed()
int _set_speed (uint8_t motor, int value)
L298 driver module using PWM signals and motor orientation
Parameters
value can be negative or positive for direction
Parameters
[in] motor motor MA or MB.
[in] value speed value
 {
     if(value == 0)
     {
         _break_motor(motor);
         return value;
     }
     if(value < 0)
     {
         if (motor == MA)
         {
             _set_pwm_0A(-1*value);
             _set_pwm_1A(0);
         }
         else if (motor == MB)
         {
             _set_pwm_0B(0);
             _set_pwm_1B(-1*value);
         }
     }
     else if(value > 0)
     {
         if (motor == MA)
         {
             _set_pwm_0A(0);
             _set_pwm_1A(value);
         }
         else if (motor == MB)
         {
             _set_pwm_0B(value);
             _set_pwm_1B(0);
         }
     }
     return value;
 }
References _break_motor().
Referenced by _command().
_update_controller()
int16_t _update_controller (uint8_t motor)
Update a control iteration for a discrete PID controller for the DC motor
Parameters
[in] motor motor MA or MB.
 {
     int16_t ref, sen,u;
     ref = _ref(motor);
     sen =   (int16_t) _sens(motor);
     u = pid_Controller(ref,sen, &pidData);
     _command(motor, u);
     if (DEBUG_CONTROLLER)
     {
         printf("%d - %d - %d\n",ref, sen, u);
     }
     return u;
 }
References _ref(), _sens(), and pid_Controller().